### ISSUE TITLE
Release version 1.0

### ISSUE THREAD

**Issue by satrapu** [satrapu/church-management-jee#1]
Version 1.0 of Church Management application will contain the following features:
- [x] JSF front-end running on JEE 7 application servers (GlassFish & Wildfly) - see issue #2 
- [ ] Manage persons (CRUD for first/middle/last names and e-mail address) - see issue #3
- [ ] Manage discipleship availability of these persons (available as teacher or disciple) - see issues #4 & #5
- [ ] Manage teacher & disciple pairs - see issue #6 
- [ ] Authenticate users (no CRUD for users at the moment, only database hard-coded records via SQL scripts) - see issue #7
- [x] Set-up CI on drone.io platform - see issue #8
- [ ] Deploy application to OpenShift platform - see issue #9
- [ ] Deploy application to Heroku - see issue #11
